### ISSUE TITLE
HistoryDataManager 사용법

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#12]
# HistortyDataManager.cs
![image](https://user-images.githubusercontent.com/28949163/177027141-e31d3633-2832-495d-b07f-0f5f53e823fb.png)
* HistoryDataManager는 싱글톤으로 설계됨
* 종이조각 보유여부, 플레이타임, 스턴횟수, 재시작횟수를 관리함
* 실질적으로 게임에 관여하는 객체는 instance.histortyData
# HistoryData.json
![image](https://user-images.githubusercontent.com/28949163/177027187-78f938b5-8d40-4a22-b7fb-ac0138b17ccd.png)
* HistoryData를 저장하는 json파일
* 처음 게임 시작시 초기값은 전부false, 0, 0, 0
* 게임 종료 및 로비화면으로 이동 시 자동으로 json파일이 업데이트됨

# 종이조각 획득
![image](https://user-images.githubusercontent.com/28949163/177027308-52447ea8-a054-416a-ba74-391ecb604366.png)

```C#
// 1번 종이조각획득 시
// 인덱스가 0부터 시작하는 것에 유의!!
HistoryDataManager.instance.SetPaperTrue(0);
```

# 플레이타임, 스턴횟수, 재시작횟수 증가
![image](https://user-images.githubusercontent.com/28949163/177027350-65a2935d-ad54-47da-8694-887c1a172e95.png)
```C#
// 스턴 횟수와 재시작 횟수를 각각 1씩 증가
HistoryDataManager.instance.AddStunCount(1);
HistoryDataManager.instance.AddRestartCount(1);
// 게임 플레이 시간을 초 단위로 반영
Stopwatch stopwatch = new Stopwatch()
void Start()
{
    stopwatch.Start();
    ...
}
...
void GameEnd()
{
    stopwatch.Stop();
    HistoryDataManager.instance.AddPlayTime(stopwatch.Elapsed.seconds);
   ...
}
```

**Comment by JangHanjun** [comment]
HistoryDataManager에 아래 함수 추가했음

```
    public bool GetPaperTrue(int _val)
    {
        return historyData.activeNodes[_val];
    }
```

**Comment by JangHanjun** [comment]
## 최소 시간을 위한 필드 추가

```
public HistoryData(bool[] _activeNodes, int _playTime, float _minPlayTime, int _stunCount, int _restartCount)
{
    activeNodes = _activeNodes;
    playTime = _playTime;
    minPlayTime = _minPlayTime;
    stunCount = _stunCount;
    restartCount = _restartCount;
}
public float minPlayTime;

```

## 최소 시간 저장 필드 추가

```
public void AddPlayTime(float _val)
{
    historyData.playTime += (int)_val;

    if(_val < historyData.minPlayTime)
    {
        historyData.minPlayTime = _val;
    }
}
```
