### ISSUE TITLE
[QA] 1스테이지에서 2스테이지로 넘어갈 수 있는 방법이 없음

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#49]
![image](https://user-images.githubusercontent.com/28949163/196840291-ede5dae4-18e4-4249-bf99-ecb265f7d556.png)
해당 이미지에 체크된 위치쯤에 타일 하나정도는 있어야 할 듯 함

**Comment by JangHanjun** [comment]
그때 테스트 한걸론 왼쪽에서 넘어가는 식으로 되었던거 같은데.

만약 좀 어럅다 싶으면 타일 3칸 정도 찍어두면 좋을듯?

**Comment by SoinDosa** [comment]
@JangHanjun 왼쪽에서 어케 넘어감?? 아무리 해봐도 안되든데

**Comment by JangHanjun** [comment]
저 한칸짜리 블럭에 여의주 두고 올라간거 같은데 지금 레벨이 좀 바뀐건가?

**Comment by JangHanjun** [comment]
일단 빌드 전에 빨간색 표시 칠한곳에 높이 1 가로 3 정도 타일 찍어서 배포해야할듯. 나중에 한번 볼께

**Comment by SoinDosa** [comment]
가능은 한데 난이도가 심히 어렵네, 일단 보류해보는걸로
