### ISSUE TITLE
[QA] 2스테이지 플레이어 이동 불가지역 확인

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#50]
![image](https://user-images.githubusercontent.com/28949163/196855849-ba8cfa33-2d36-4a27-862c-7973962b2ae9.png)
해당 지역으로 날아갈 경우 플레이어가 이동할 수단이 없음, △블럭을 위치시키거나 플레이어 자율적으로 움직일 수 있는 기능이 필요해보임

**Comment by JangHanjun** [comment]
이 부분은 추후 준하님한테 알려드리는 방향으로 해야 할듯?

아직 튜토리얼이 잘 안되어있어서 그렇긴 한데 r누르면 아마 위치 초기화는 될겨

**Comment by SoinDosa** [comment]
오호 확인
