### ISSUE TITLE
[QA] 건의 : BGM 교체기능 및 효과음

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#51]
# BGM 교체 기능
현재는 추락할 경우 20% 확률로 랜덤bgm으로 변경하는 로직인데 운나쁘게 계속 bgm이 동일할 경우 플레이가 단조로워지는 느낌이 있음, 
- 추락할 경우 확률을 50%로 증가
- 씬을 옮길 때마다(로비씬 <-> 게임씬) BGM을 랜덤하게 바꾸는 기능

이 있으면 어떨까 제안
# 효과음
효과음이 아직 없어서 꽤 밋밋함
- 추락할 때
- 여의주를 던질 때
- NPC와 만났을 때

효과음을 재생하면 어떨까 제안함

**Comment by JangHanjun** [comment]
## BGM 교체

일단 스턴 시간이 늘어나서 기존 20%가 좀 단조로운 느낌이 들기도 하는듯? 그래서 확률 40~50%로 늘리면 좋을거 같긴 해

```cs
        public void PlayerStuned(bool isStuned)
        {
            //...
            if(UnityEngine.Random.Range(0.0f, 1.0f) < 0.2f)  // -> 여기 0.2f를 0.4f~0.5f로 변경하면 될듯!
                SoundManager._instance.PlayRandomBGM();
            //...
        }
```

## 효과음

아직 효과음을 구할만한 플랫폼이 없어서 넣지 않았는데 추후에 효과음 필요한 부분들 모아서 소리 구한 뒤 효과음 컴포넌트를 제작해서 사용해보는걸 생각해 보겠음
