### ISSUE TITLE
[QA] 2스테이지 버그 발견

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#60]
![image](https://user-images.githubusercontent.com/28949163/200541391-165c4df1-dd09-4196-89fa-9946013ef949.png)
* 플레이어가 잘못해서 멧돼지 위로 착륙할 경우 스턴이 풀리지 않음
* 멧돼지 충돌판정을 없애보겠음

**Comment by JangHanjun** [comment]
이건 몰랐네
NPC들처럼 멧돼지 충돌 판정만 없애면 무난할거 같은데
