### ISSUE TITLE
SoundManager 사용하는법[쉬움주의!]

### ISSUE THREAD

**Issue by SoinDosa** [NoHornDragon/NoHornDragon_GameDev#9]
![image](https://user-images.githubusercontent.com/28949163/172837239-c0ddc3b5-958e-4fed-b461-cde53f9a7080.png)
* SoundManager는 DontDestroy 싱글톤 객체임

# Sound 추가하기
![image](https://user-images.githubusercontent.com/28949163/172837359-cb92ec44-187f-483b-8cf3-079ad9a6d262.png)
* SoundManager에는 BgmSounds, EffectSounds라는 <Sound> List가 존재
* 사운드를 추가하고 싶다면 List의 Size를 늘린 다음 Name에는 사운드의 이름을(사용 장소 등), Clip에는 SoundClip을 넣어주면 됨
* 싱글턴 객체이므로 다른 씬에는 존재하지 않음, 그러므로 Lobby Scene에서 작업해주도록 하자

# Sound 실행하기
![image](https://user-images.githubusercontent.com/28949163/172837678-e8d0c6f1-3677-4e32-92a5-89031ee1b02c.png)
* SoundManager.instance.PlayBGM(_name, _isFade)
    * BGM을 실행할 수 있는 메서드임, _isFade는 페이드인 효과를 줄 지 말지 결정할 수 있음
* SoundManager.instance.PlayEffect(_name)
    * Effect를 실행할 수 있는 메서드임, 페이드인 효과는 존재하지 않음
* SoundManager.instance.StopBGM(_isFade)
    * BGM을 중지하는 메서드, _isFade로 페이드아웃 효과여부를 결정할 수 있음

**Comment by SoinDosa** [comment]
@JangHanjun 작업하기 전, 수정된 InGameUI_Modify 프리팹 사용할 것!

**Comment by JangHanjun** [comment]
## 사운드 매니저 수정

- 일단 기존 SoundManager 에서 foreach를 활용해 이름으로 검색하는 부분은 비효율적이라 판단. 때문에 기존 play의 경우 인덱스 접근으로 변경한 뒤 사용
- 이후 SFX 플레이의 경우에도 같은 방식 적용 예정
- 추가적으로 SFX의 sound volume의 경우 unity AudioMixer를 통해 조절할 예정
